site/content/capabilities/training-courses/courses/scrumorg-professional-scrum-master/index.md
site/layouts/partials/course-parts/syllabus-single.html

40 Topic/extras

---

site/content/capabilities/mentor-programs/product-development-mentoring-program/index.md
site/content/capabilities/mentor-programs/product-management-mentor-program/index.md
site/layouts/course-vendors/list.html
site/layouts/delivery-audiences/list.html
site/layouts/partials/infrastructure/breadcrumbs.html

📝 (content): add weight to mentor program pages for consistent ordering
♻️ (layouts): refactor course and vendor list templates for better card handling
✨ (layouts): add new delivery audiences list template for improved navigation
💡 (breadcrumbs): update breadcrumbs to support delivery audiences taxonomy
The mentor program pages now include a weight attribute to ensure consistent ordering in listings. The course and vendor list templates are refactored to handle card rendering more efficiently, improving maintainability and readability. A new template for delivery audiences is introduced to enhance navigation and user experience. Breadcrumbs are updated to support the new delivery audiences taxonomy, ensuring accurate navigation paths.

Create pages for accountability

---

.github/workflows/main.yaml

The workflow now includes a step to copy all static web app configuration files matching the pattern "staticwebapp.config.*.json" to the "./public/" directory. This change ensures that any additional configuration files are included in the deployment process, providing greater flexibility and accommodating multiple environments or configurations.

🔧 (main.yaml): enhance workflow to copy all static web app config files

---

.github/workflows/main.yaml
site/content/company/terms-of-business/index.md
site/hugo.yaml
site/layouts/_default/baseof.html
site/layouts/partials/card.html
site/layouts/partials/headline.html
site/layouts/partials/infrastructure/footer.html
site/layouts/partials/infrastructure/header.html
site/layouts/robots.txt
site/static/css/main.css
site/static/robots.txt

📝 (footer.html): update NKD Insights™ link to correct URL path
The link to NKD Insights™ in the footer is updated to remove the incorrect "/resources" segment from the URL path. This change ensures that users are directed to the correct page when they click on the link, improving navigation and user experience on the site.

Chatch Some of the Little Errors That were missed!

---

site/content/capabilities/mentor-programs/product-development-mentoring-program/index.md
site/content/capabilities/mentor-programs/product-management-mentor-program/index.md
site/content/capabilities/training-courses/_index.md
site/content/company/_index.md
site/content/course-topics/azure-devops-training-courses/_index.md
site/content/course-topics/kanban-training-courses/_index.md
site/content/course-topics/product-training-courses/_index.md
site/content/course-topics/scrum-training-courses/_index.md
site/content/resources/blog/_index.md
site/content/resources/newsletters/_index.md

🌐 (content): add aliases for improved URL accessibility and SEO
Add aliases to various content pages to enhance URL accessibility and improve search engine optimization. This change ensures that users can access content through multiple URL paths, accommodating potential changes in URL structure and improving user experience by preventing broken links. It also aids in maintaining SEO rankings by preserving link equity from old URLs.

🌐 (content): add aliases for improved URL accessibility and SEO

---

site/content/resources/guides/evidence-based-management-guide-2020/index.md
site/content/resources/guides/evidence-based-management-guide/index.md
site/content/resources/guides/evidence-based-portfolio-management/index.md
site/content/resources/guides/kanban-guide-for-scrum-teams/index.md
site/content/resources/guides/manifesto-for-agile-software-development/index.md
site/content/resources/guides/nexus-framework/index.md
site/content/resources/guides/scrum-guide/index.md
site/content/resources/practices/accountabilities-for-the-scrum-team/index.md
site/content/resources/practices/definition-of-done-dod/index.md
site/content/resources/practices/definition-of-ready-dor/index.md
site/content/resources/practices/metrics-reports/index.md
site/content/resources/practices/product-backlog/index.md
site/content/resources/practices/product-increment/index.md
site/content/resources/practices/product-scorecard/index.md
site/content/resources/practices/professional-sprint-planning-event/index.md
site/content/resources/practices/service-level-expectation-sle/index.md
site/content/resources/practices/site-reliability-engineering-sre/index.md
site/content/resources/workshops/customer-working-agreement/index.md
site/content/resources/workshops/definition-of-done/index.md
site/content/resources/workshops/sprint-review-1/index.md
site/content/resources/workshops/the-importance-of-batch-to-optimise-flow/index.md

📝 (content): update alias paths for resources and workshops
Update alias paths in markdown files to include leading slashes. This ensures consistency and improves URL resolution, making it easier for users to access resources and workshops through predictable and standardized paths. This change enhances the site's SEO and usability by aligning with common URL structuring practices.

Redirect Checks

---

site/content/resources/methods/_index.md
site/content/resources/methods/one-engineering-system/index.md

Remove outdated content and update the methods documentation to reflect current practices. The changes include setting the draft status to false for both the "Technically Agile: Methods" and "One Engineering System" pages, indicating they are ready for publication. The "One Engineering System" page is updated to provide a clearer explanation of the strategy and its benefits, emphasizing the importance of adapting workflows to the specific capabilities of the tools in use. This ensures the documentation is accurate, relevant, and ready for public viewing, providing users with up-to-date information on the methods and tools available.

📝 (content): update methods documentation to reflect current practices

---

.github/workflows/shedule.yml

Introduce a new GitHub Actions workflow to automate the process of finding the latest semantic version tag and triggering another workflow. This is scheduled to run daily at midnight. The workflow checks out the code, generates a GitHub App token, finds the latest semantic version tag using PowerShell, and triggers another workflow using the found tag. This automation helps in maintaining a consistent release process and ensures that the latest version is always used for subsequent workflows.

🔧 (schedule.yml): add GitHub Actions workflow to find latest tag and trigger another workflow

---

.testData/test-file.json
site/hugo.yaml
site/layouts/_default/section.rss.xml
site/layouts/partials/functions/keywords.html
site/layouts/partials/infrastructure/seo.html
site/layouts/partials/publications/craft.html

Introduce a new RSS feed configuration to enhance content distribution and user engagement. The RSS feed is now generated using a custom template, allowing for better control over the feed's structure and content. Additionally, refactor the keyword handling logic by moving it to a partial template, improving maintainability and reusability across different parts of the site. This change also ensures that keywords are consistently applied, enhancing SEO performance.

✨ (site): add RSS feed support and improve SEO keyword handling

---

site/content/resources/blog/2023/2023-10-17-the-7-deadly-sins-of-agile-a-grecian-odyssey-through-modern-software-development/index.md

📝 (blog): update blog post structure and video links for better readability and engagement
The blog post is restructured to improve readability by using consistent headings for each section. Video links are updated to use a more engaging format, encouraging readers to watch the related content. This enhances the user experience by making the content more organized and visually appealing, while also providing easy access to supplementary video material.

Update: The 7 Deadly Sins of Agile: A Grecian Odyssey through Modern Software Development

---

site/layouts/partials/infrastructure/footer.html
site/layouts/partials/infrastructure/head.html
site/layouts/partials/infrastructure/header.html

✨ (footer.html, head.html, header.html): add consent preferences link and update search functionality
Add a "Consent Preferences" link to the footer to allow users to manage their consent settings, enhancing user control over privacy. Replace Algolia search with DocSearch for improved search capabilities and maintainability. Update icons in the header for better visual representation and accessibility. These changes aim to improve user experience and align with privacy regulations.

consent preferences 

---

site/content/resources/videos/youtube/NgoP5W5y7Gs/index.md
site/content/resources/videos/youtube/r2G-NrSIj2k/index.md

Video page is: /resources/videos/NgoP5W5y7Gs

Security by design. Building secure software (NgoP5W5y7Gs)

---

site/content/company/working-with-us/index.md

feat(working-with-us): add new content page outlining partnership models and terms of business to enhance customer understanding of engagement options

Working with Us

---

site/content/capabilities/azure-devops-migration-services/index.md
site/layouts/partials/page-sections/sections-consulting-options.html
site/layouts/partials/page-sections/sections.html

feat(azure-devops): remove outdated courses section and add consulting options for Azure DevOps services to enhance user guidance and support
chore(templates): create new partial for consulting options to improve code organization and maintainability

Add methodology and options to Sections

---

site/content/company/communicating-with-us/index.md
site/content/company/contact/index.md
site/content/company/working-with-us/index.md

feat(communicating-with-us): add new page for communication guidelines with clients and partners to enhance collaboration
fix(contact): add alias for booking page to improve navigation
fix(working-with-us): update alias for working page to reflect new URL and improve clarity

Page: Communicate with Us

---

site/content/resources/blog/2025/2025-01-03-definition-of-done-objective-vs-subjective/index.md

docs(blog): add conclusion and call to action to the Definition of Done article to enhance reader engagement and provide closure

Adding CTA

---

site/content/resources/videos/youtube/DSIXtHZTirA/index.md

Convert YouTube description to Blog Post

Update Performance Engineering blog post

---

site/content/resources/videos/youtube/IZ-FlBbGaSY/index.md

Convert YouTube Description to Blog Post

Update Continuous Integration and Continuous delivery blog post

---

site/content/resources/videos/youtube/DSIXtHZTirA/index.md

Update YouTube description to Blog Post

 Your partner in developing Engineering Excellence

---

site/content/resources/videos/youtube/BAwBXYtKj7o/index.md

Update YouTube description to blog post

Technical Debt Management for Long-Term Quality

---

.powershell/single-use/blog/Update-BlogFrontMatter.ps1
.powershell/single-use/resources/Update-ReourcesFrontMatter.ps1
site/content/resources/blog/2025/2025-02-06-stop-promoting-branches/index.md
site/content/resources/blog/2025/2025-02-06-testing-in-production-maximises-quality-and-value/index.md
site/content/resources/blog/2025/2025-02-17-no-such-thing-as-a-junior-scrum-master/index.md

Testing in production, is about structured, observable releases that allow for fast feedback, controlled exposure, and rapid course correction, ensuring quality without sacrificing speed.
This includes the following posts:
- [Testing in Production Maximises Quality and Value](https://yellow-pond-042d21b03-267.westeurope.5.azurestaticapps.net/resources/blog/testing-in-production-maximises-quality-and-value/)
- [Stop Promoting Branches](https://yellow-pond-042d21b03-267.westeurope.5.azurestaticapps.net/resources/blog/stop-promoting-branches/)
Feedback can be provided as a PR review or as text below.

NEW POST: Testing in Production Maximises Quality and Value

---

site/content/resources/blog/2025/2025-03-03-measuring-individual-cycle-time-is-killing-your-flow/index.md

📝 (blog): update punctuation for consistency in list formatting
The changes standardize the punctuation in the list by replacing em dashes with hyphens for consistency. Additionally, the description for "Process Cycle Efficiency (PCE)" is updated to clarify the distinction between active work time and non-value-added time. This improves readability and ensures uniformity in the presentation of key concepts.

Update: Why Measuring Individual Cycle Time is Killing Your Flow (And What to Do Instead)

---

.powershell/_includes/ImagesToBlobStorage.ps1
.powershell/dev/Sync-BlobStorageImages.ps1

♻️ (ImagesToBlobStorage.ps1, Sync-BlobStorageImages.ps1): refactor logging and improve URL handling logic
Refactor the logging mechanism to use `Write-InfoLog` instead of `Write-Host` for better log management and consistency. Enhance the URL handling logic in `Rewrite-ImageLinks` to ensure paths are correctly updated only when they match the allowed pattern. This change improves the clarity and maintainability of the script by ensuring that only valid URLs are processed and others are logged for debugging.

♻️ Refactor Logging & Improve URL Handling in Blob Storage Scripts

---

site/layouts/partials/publications/share-bar.html
site/layouts/resources/blog.html
site/layouts/resources/single.html
site/layouts/resources/video.html
site/static/css/resources.css

Refactor the HTML structure to enhance the layout's flexibility and responsiveness. Adjust the share bar's padding and update the button's title for better user engagement. Modify CSS to improve text readability and ensure consistent styling across different sections. These changes aim to provide a more visually appealing and user-friendly interface, enhancing the overall user experience on the site.

💄 (UI): improve layout and styling for publications and resources

---

site/content/company/terms-of-business/index.md

This pull request updates the Terms of Business document to reflect revised service descriptions, compliance details, and liability terms. The changes enhance clarity, align with legal requirements, and refine the messaging to better communicate the company's offerings.
* Updated the description and content to emphasize "real agility" and strategic capacity rather than task management, clarifying the value proposition of the services provided. [[1]](diffhunk://#diff-ec5eaa2738f941de286612ba93845665461b268bab19d1b76b823b7d4cec67d3L3-R3) [[2]](diffhunk://#diff-ec5eaa2738f941de286612ba93845665461b268bab19d1b76b823b7d4cec67d3L17-R17) [[3]](diffhunk://#diff-ec5eaa2738f941de286612ba93845665461b268bab19d1b76b823b7d4cec67d3L26-R32)
* Added a new section on UK Legal Compliance (IR35), outlining …

Terms ir35

---

site/content/company/terms-of-business/index.md

- update the per diem in the terms of business
- `git status --short`

Update per diem rate

---

.prompts/classification-analysis.md

- revise reasoning_summary description for clarity and conciseness
- emphasize relevance and fit over quality or effectiveness in the summary

📝 docs(prompts): update reasoning summary guidelines

---

site/static/css/main.css

- adjust dark-primary-color and dark-primary-color-light for better contrast
- modify primary-color and primary-color-light in dark theme for improved aesthetics

💄 style(css): update dark mode color palette

---

site/content/company/privacy/index.md
site/content/company/terms-of-business/index.md
site/layouts/company/single.html
site/layouts/partials/components/resources/share-bar.html
site/layouts/shortcodes/toc.html

This pull request introduces significant updates to the privacy policy, adds new UI elements for better user experience, and includes cross-linking between pages for improved navigation. Below is a summary of the most important changes grouped by theme.
* Expanded the privacy policy in `site/content/company/privacy/index.md` to include detailed sections on consulting practice privacy, data collection and processing, data security, consent for data transfers, and user rights regarding data. These updates ensure compliance with GDPR and enhance transparency. [[1]](diffhunk://#diff-5b383e0cc97115e0e88a80deb26c4e1913b33318fb6bc51867f1d92376b033b2L3-R67) [[2]](diffhunk://#diff-5b383e0cc97115e0e88a80deb26c4e1913b33318fb6bc51867f1d92376b033b2R79-R80) …

Updated Privacy Policy

---

site/static/css/main.css

- adjust dark mode background colors for improved contrast
- change --dark-background-color and --dark-background-color-alt values

💄 style(css): update dark mode background colors

---

site/layouts/partials/components/resources/share-bar.html
site/layouts/partials/infrastructure/head.html

This pull request updates the email subscription modal and integrates Mailchimp functionality into the site. The changes include improvements to the subscription form, updates to the Mailchimp embed code, and the addition of a new script for Mailchimp connectivity.
* Updated the subscription form in `site/layouts/partials/components/resources/share-bar.html` to include new options such as "Videos" and "Events," and added descriptions for each notification type. The form now allows users to update preferences if already subscribed.
* Changed the heading from "Subscribe" to "Subscribe or Update" and added a hidden input for tags to enhance functionality.
* Added a new Mailchimp script in `site/layouts/partials/infrastructure/head.html` for user connectivity (`mcjs`). This script integrates …

Update subscribe form

---

.github/copilot-instructions.md
docs/casestudy-section-usage.md
docs/outcomeboxes-section-usage.md
docs/sectioncta-section-usage.md
docs/textnlist-section-usage.md
site/content/outcomes/engineering-excellence/index.md
site/docs/outcomeboxes-section-usage.md
site/layouts/_default/baseof.html
site/layouts/capabilities/single.html
site/layouts/partials/page-sections/section-router.html
site/layouts/partials/page-sections/section-wrapper.html
site/layouts/partials/page-sections/sections-casestudy.html
site/layouts/partials/page-sections/sections-outcomeboxes.html
site/layouts/partials/page-sections/sections-sectioncta.html
site/layouts/partials/page-sections/sections-textnlist.html
site/static/css/main.css

This pull request introduces three new section types (`casestudy`, `outcomeboxes`, and `sectioncta`) to enhance the flexibility and visual appeal of content layouts. It also includes updates to the documentation, styling, and section routing to support these new types. Below is a breakdown of the most important changes grouped by theme.
* **`casestudy`**: Added a section type for showcasing results or achievements with icons and an optional call-to-action. Includes a dedicated partial template (`site/layouts/partials/page-sections/sections-casestudy.html`) and documentation (`docs/casestudy-section-usage.md`). [[1]](diffhunk://#diff-140fb4618efa6eb99787d1434efbd9a6655b8943abc533c648efb05c8e2bcbcaR1-R64) [[2]](diffhunk://#diff-f9a07572d1a3097268aaefd5e5ed10f6b31f40848744d8e1eb8dacb6756a20fd …

More outcomes work

---

.powershell/_includes/ClassificationHelpers.ps1
.powershell/_includes/EmbeddingRepository.ps1
.powershell/_includes/IncludesForAll.ps1
.powershell/_includes/OpenAI.ps1
.powershell/_includes/RelatedCacheHelpers.ps1
.powershell/_includes/ResourceHelpers.ps1
.powershell/_includes/TokenServer.ps1
.powershell/build/Update-ResourcesFrontMatter.ps1
.powershell/build/Update-ResourcesRelatedCache.ps1

This pull request refactors the inclusion of helper files across various PowerShell scripts by consolidating them into a single shared file, `.powershell/_includes/IncludesForAll.ps1`. It also introduces minor updates to streamline embedding repository updates and modifies resource processing paths. Below are the most important changes grouped by theme:
* Removed individual helper file inclusions from `.powershell/_includes/ClassificationHelpers.ps1`, `.powershell/_includes/EmbeddingRepository.ps1`, `.powershell/_includes/OpenAI.ps1`, `.powershell/_includes/RelatedCacheHelpers.ps1`, `.powershell/_includes/ResourceHelpers.ps1`, `.powershell/_includes/TokenServer.ps1`, `.powershell/build/Update-ResourcesFrontMatter.ps1`, and `.powershell/build/Update-ResourcesRelatedCache.ps1`. All scripts …

Powershell refactor

---

site/layouts/shortcodes/recent-resources.html

This pull request includes a small change to the `site/layouts/shortcodes/recent-resources.html` file. The change updates the hyperlink to use `.Permalink` instead of `.RelPermalink` for better URL handling.

Fic for Mailchimp newsletter links

---

site/content/company/terms-of-business/index.md

- adjust hours to show a more precise estimate
- clarify that hours are indicative and value-focused

📝 docs(terms-of-business): update weekly hours representation

---

site/layouts/partials/components/pages/header-buttons.html
site/static/css/resources.css

- change class name from 'buttons' to 'header-buttons'
- update button styling to 'btn-outline-secondary me-1'
💄 style(css): enhance header button styles
- apply consistent text and border color for header buttons
- add hover and focus effects for header button styles

💄 style(header-buttons): update button classes for header

---

site/layouts/partials/main-menu-resources.html
site/layouts/resources/list.html

- rename $ResourceTypes to $ResourceTypeFilter for clarity and consistency
- update conditional checks to use the new variable name

♻️ refactor(resources): update variable naming for consistency

---

site/content/resources/guides/evidence-based-management-guide-2020/index.md
site/content/resources/guides/evidence-based-management-guide/index.md
site/content/resources/guides/evidence-based-portfolio-management/index.md

- add short_title to guides for better navigation
- adjust aliases for improved link consistency
- update slugs for clarity and brevity

📝 docs(guides): add short titles and adjust aliases

---

.github/copilot-instructions.md
docs/syllabus-system.md

- introduce guidelines for selecting learning resources
- prioritize NKD Agility, Scrum.org, and reputable sources
- outline resource quality standards and implementation in syllabus
- provide best practices for syllabus creation

📝 docs(syllabus-system): add learning resource selection guidelines

---

site/layouts/partials/delivery-parts/syllabus-single.html

- remove unnecessary line breaks for cleaner HTML structure
- improve readability by consolidating text into single lines

💄 style(syllabus): format HTML content for consistency

---

site/content/company/privacy/index.md

- add Copilot usage for Microsoft Office 365 and GitHub
- include ChatGPT details for AI-supported engineering
- emphasize enterprise-grade AI for privacy and data governance

📝 docs(privacy): update privacy policy with AI tool usage

---

site/content/resources/guides/evidence-based-management-guide/_index.md
site/content/resources/guides/scrum-guide/2010.2/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nkdAgility/NKDAgility.com/546)

Fix 1 versioned guide

---

.data/classifications.json
site/content/resources/blog/2025/2025-09-22-estimation-trap-in-software-delivery/index.md

This pull request updates the blog post titled "The Estimation Trap in Software Delivery" to refine its messaging, improve clarity, and add new content. Key changes include a more descriptive title, additional contributor information, improved phrasing for key points, and the inclusion of a comparison table to highlight alternative metrics.
* Updated the title to be more descriptive: "The Estimation Trap: How Tracking Accuracy Undermines Trust, Flow, and Value in Software Delivery" (`site/content/resources/blog/2025/2025-09-22-estimation-trap-in-software-delivery/index.md`).
* Added contributor details, including the name, GitHub username, and external link for Ralph Jocham (`site/content/resources/blog/2025/2025-09-22-estimation-trap-in-software-delivery/index.md`).
* Adjusted phrasing …

Refactor blog post with feedback from Ralph and Nigel

---

site/content/resources/blog/2025/2025-09-22-estimation-trap-in-software-delivery/index.md

This pull request makes several improvements to the content of a blog post titled "The Estimation Trap: How Tracking Accuracy Undermines Trust, Flow, and Value in Software Delivery." The changes focus on refining the language for clarity, enhancing the accuracy of technical explanations, and improving the presentation of key concepts.
* Updated the blog title to use double quotes instead of single quotes for consistency with other posts. (`site/content/resources/blog/2025/2025-09-22-estimation-trap-in-software-delivery/index.md`, [site/content/resources/blog/2025/2025-09-22-estimation-trap-in-software-delivery/index.mdL2-R2](diffhunk://#diff-f0aac9bb973ae7f803e16afb57588c8f10f87084d714049ee0d4881b1a829f05L2-R2))
* Reworded sentences to improve readability and clarity, such as refining the …

Gramer fixes from nigel

---

site/content/company/communicating-with-us/index.md

This pull request revises and expands the communication and collaboration instructions for working with NKD Agility, focusing on clearer guidance, streamlined language, and new information about Microsoft Teams Shared Channels. The updates improve clarity, reduce redundancy, and add practical steps for secure collaboration setup.
Key content and documentation improvements:
* Simplified and clarified language throughout the document to make instructions more concise and easier to follow.
* Added a comprehensive section on using Microsoft Teams Shared Channels (Teams Connect), including prerequisites, step-by-step setup, and troubleshooting tips.
* Updated the Cross-Tenant Access configuration steps for Microsoft Entra ID to be more actionable and specific, emphasizing B2B direct connect …

Refactor communication and security setup instructions for clarity and consistency

---

.powershell/build/Get-TrainingRateTable.ps1
site/content/capabilities/training-courses/scrumorg-professional-scrum-product-backlog-management-skills/syllabus.yaml
site/data/trainingRates.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nkdAgility/NKDAgility.com/586)

Fix path formatting in training rates JSON for consistency

---

.powershell/build/Get-TrainingRateTable.ps1
site/content/capabilities/training-courses/prokanban-applying-flow-metrics-for-scrum/index.md
site/content/capabilities/training-courses/prokanban-applying-metrics-for-predictability/index.md
site/content/capabilities/training-courses/prokanban-applying-professional-kanban/index.md
site/content/capabilities/training-courses/scrumorg-professional-scrum-master-and-product-owner/index.md
site/content/capabilities/training-courses/scrumorg-professional-scrum-master/index.md
site/content/capabilities/training-courses/scrumorg-professional-scrum-product-owner-advanced/index.md
site/data/trainingRates.json

This pull request introduces improvements to how training course session counts are determined and synchronizes those values across course markdown files and the training rates data. The main change is that session counts are now consistently sourced from both the course front matter and syllabus files, with fallback logic if either is missing. Several course markdown files have been updated to explicitly include `sessionCount`, and the training rates JSON has been updated to reflect accurate session counts and rates for all courses.
**Session Count Calculation and Data Synchronization**
* Refactored the session count calculation logic in `Get-TrainingRateTable.ps1` to use the maximum value from either the front matter or the syllabus file, with improved error handling if either source is …

Add training courses and update rates in trainingRates.json

---

.resources/capabilities/2025/capabilities.2025-09-23.engineering-excellence-in-one-hour-a-week.human.md
.resources/capabilities/2025/capabilities.2025-09-23.technical-leadership-in-one-hour-a-week.human.md
.resources/capabilities/capabilities.2025.json
site/content/capabilities/_index.md
site/content/capabilities/engineering-excellence-in-one-hour-a-week/index.md
site/content/capabilities/technical-leadership-in-one-hour-a-week/index.md

This pull request introduces two new capability offerings—"Engineering Excellence in One Hour A Week" and "Technical Leadership in One Hour A Week"—and updates the capabilities overview to highlight these services. The changes add detailed descriptions and marketing content for each new capability, and reorganize the main capabilities listing to feature them more prominently, ensuring they are visible and accessible to users exploring consulting services.
**New Capability Resources:**
* Added `engineering-excellence-in-one-hour-a-week` resource with a detailed guide, value proposition, and call to action for weekly, focused engineering improvement sessions. (.resources/capabilities/2025/capabilities.2025-09-23.engineering-excellence-in-one-hour-a-week.human.md, …

1 hour a week

---

site/content/resources/guides/kendall-guide/index.md

This pull request makes minor updates to the Kendall Guide resource page. The changes focus on simplifying the short title and improving licensing transparency for the content.
Content and licensing updates:
* Simplified the `short_title` in the frontmatter from "Kendall Guide: Framework for AI Adoption" to "Kendall Guide" for clarity and brevity.
* Added a Creative Commons Attribution-ShareAlike 4.0 International License statement to the bottom of the page, clarifying usage rights and encouraging sharing and adaptation with attribution.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nkdAgility/NKDAgility.com/596)

Kendall Guide
