site/layouts/partials/course-parts/syllabus-single.html

The learning resources section is now expanded by default to improve user experience. This change allows users to immediately view the resources without needing to click to expand, making the information more accessible and reducing the number of interactions required to access important content.

✨ (syllabus-single.html): expand learning resources section by default

---

site/layouts/_default/baseof.html
site/layouts/index.html
site/layouts/partials/page-sections/sections-cards.html
site/layouts/partials/trustpilot/scrumorg-trustpilot-carousel.html

✨ (layouts): integrate Trustpilot carousel for enhanced user engagement
Introduce a new Trustpilot carousel widget to the site layout to improve user engagement and provide social proof. The carousel is added to the base layout for all pages except the homepage, and directly to the index.html for the homepage. This change replaces the static Trustpilot section with a dynamic carousel, offering a more interactive and visually appealing experience. The new partial
'scrumorg-trustpilot-carousel.html' is created to encapsulate the carousel widget, ensuring modularity and reusability across the site.

Emergancy release

---

site/layouts/partials/jsonld/delivery.html

🌐 (delivery.html): update course location and schedule details in JSON-LD
Change the course location from "Example University" to "Microsoft Teams" to reflect the shift to online delivery. Adjust the course schedule for "Traditional" and default experiences to have a longer duration but fewer repeat counts, aligning with the new online format. These changes ensure the JSON-LD data accurately represents the current course delivery method and schedule.

update course location and schedule details

---

.github/workflows/shedule.yml

The cron schedule in the GitHub Actions workflow is updated to run every 3 hours instead of once daily. This change allows for more frequent execution of the workflow, which can be beneficial for tasks that require regular updates or checks throughout the day.

🔧 (schedule.yml): update cron schedule to run every 3 hours

---

site/layouts/partials/publications/craft.html
site/layouts/partials/resources-card.html

Enhance the user interface by displaying badges for draft, scheduled, and expired publications. This provides users with clear visual cues about the status of each publication. Drafts are marked with a warning badge, scheduled publications with a danger badge, and expiry dates are shown if applicable. This improves content management and user awareness of publication timelines.

✨ (craft.html, resources-card.html): add draft, scheduled, and expiry indicators for publications

---

site/layouts/partials/infrastructure/head.html

Introduce a conditional check for the `videoId` parameter to customize the `giscus:backlink` meta tag. This change ensures that when a page has a `videoId`, the backlink points to the specific video resource URL, enhancing SEO and user navigation. If no `videoId` is present, the backlink defaults to the page's relative permalink.

✨ (head.html): add conditional backlink meta tag for video pages

---

.github/workflows/main.yaml
site/layouts/partials/infrastructure/publish-redirects.html

🔧 (main.yaml): disable BuildApi job and fix jq command for merging configs
📝 (publish-redirects.html): comment out unused redirect logic for clarity
The BuildApi job is temporarily disabled by setting its condition to false, likely for testing or maintenance purposes. The jq command is corrected to include the $routesConfig file, ensuring all necessary configurations are merged. In the publish-redirects.html file, the redirect logic is commented out, indicating it is not currently needed but preserved for potential future use. This improves the clarity and maintainability of the code.

Update with smaller routes file

---

site/layouts/partials/infrastructure/seo.html

🐛 (seo.html): fix potential nil pointer issue with socialProfiles 
Ensure that the `socialProfiles` parameter defaults to an empty slice if not provided. This prevents potential nil pointer errors when appending to the `allProfiles` slice. The change enhances the robustness of the SEO template by ensuring that the `sameAs` field always processes a valid list of profiles, even if none are specified in the parameters.

Invalid URL in field 'sameAs' (in 'mainEntity')

---

site/layouts/partials/infrastructure/footer.html

♻️ (footer.html): remove hardcoded email_id from Sendinblue configuration
The hardcoded email_id in the Sendinblue configuration is removed to enhance privacy and security. This change prevents exposing sensitive information in the source code and allows for more flexible configuration management.

Fix for Breva's silly documentation

---

site/layouts/_default/baseof.html
site/layouts/partials/infrastructure/footer.html
site/layouts/partials/infrastructure/head.html
site/layouts/partials/infrastructure/seo.html

✨📝 (baseof.html, footer.html, head.html, seo.html): integrate GoogleTag Manager and remove redundant scripts
Integrate Google Tag Manager (GTM) to enhance tracking and analytics capabilities. GTM provides a more flexible and centralized way to manage tags and scripts. Remove the Brevo and Google Analytics scripts to avoid redundancy and potential conflicts, as GTM can handle these functionalities. Additionally, fix a minor formatting issue in the SEO title tag for consistency.

Replace old Google Tag Manager Code

---

site/layouts/partials/infrastructure/publish-redirects.html

♻️ (publish-redirects.html): remove unused JSON output generation for routes
The generation of a JSON output for routes was removed as it was not being used in the current implementation. This cleanup helps in reducing unnecessary code and potential confusion, improving the maintainability of the codebase.

Remove routes file entirely

---

.powershell/_includes/ImagesToBlobStorage.ps1
.powershell/dev/Sync-BlobStorageImages.ps1

fix(ImagesToBlobStorage.ps1): ensure uniqueness of image URLs by using an array to track already included URLs
chore(Sync-BlobStorageImages.ps1): update local image path to a relative path for better portability and remove commented-out code for clarity

Fix for duplicate image URL

---

site/content/company/supplier-bank-account-details/index.md
site/hugo.yaml

feat(supplier-bank-account-details): add resources section with PDF proof of account details for better documentation
chore(hugo.yaml): remove unnecessary _build configuration to simplify settings

Fix for missing PDF

---

site/layouts/partials/infrastructure/seo.html

feat(seo.html): enhance Open Graph and Twitter meta tags to use resource matching for images
This change allows the application to dynamically select the appropriate image for Open Graph and Twitter meta tags based on the provided preview parameter, improving SEO and social media sharing capabilities. If no specific image is found, it falls back to a default image.

Fix for Preview images on Websites

---

site/layouts/resources/blog.html

Add the Elevenlabs Text to Speech AudioNative Player widget to the blog layout to enhance accessibility and user experience by providing an audio version of the blog content. This change allows users to listen to the blog posts, catering to those who prefer auditory content or have visual impairments. The widget is embedded with a script and styled to fit within the existing layout.

✨ (blog.html): integrate Elevenlabs Text to Speech AudioNative Player

---

site/content/resources/blog/2025/2025-02-17-no-such-thing-as-a-junior-scrum-master/index.md

📝 (blog): update blog content to emphasize the importance of masteryin the Scrum Master role
The blog post is updated to strengthen the argument against the concept of a "junior" Scrum Master. It draws parallels with other senior roles, emphasizing that mastery and experience are essential. The changes highlight the necessity for Scrum Masters to have firsthand experience within a Scrum Team and the ability to engage with technical aspects, even if not coding daily. The update also critiques the practice of hiring underqualified Scrum Masters to cut costs, which undermines the role's effectiveness. These additions aim to clarify the expectations and responsibilities of a Scrum Master, reinforcing the idea that it is not an entry-level position.
SEE POST: …

UPDATE: There Is No Such Thing as a "Junior" Scrum Master [2025-02-17T09:00:00]

---

.powershell/_includes/ClassificationHelpers.ps1
.powershell/_includes/HugoHelpers.ps1
.powershell/single-use/resources/Update-Catagories.ps1
site/content/categories/code-and-complexity.md

♻️ (ClassificationHelpers.ps1): refactor metadata extraction to use Get-HugoMarkdownList
✨ (code-and-complexity.md): add Instructions field for more detailed guidance
📝 (HugoHelpers.ps1): rename function for clarity and remove JSON conversion
Refactor the metadata extraction process to directly use the Get-HugoMarkdownList function, simplifying the code and removing unnecessary JSON conversion. This change improves the maintainability and readability of the script. The Instructions field is added to code-and-complexity.md to provide more detailed guidance on the category's intended use, ensuring discussions remain focused on technical topics. The function Get-MarkdownMetadata is renamed to Get-HugoMarkdownList for better clarity and alignment with its purpose. Commented out a line in …

Update instructions for categories

---

site/layouts/index.html
site/layouts/partials/infrastructure/breadcrumbs.html
site/layouts/partials/taking-on-new-client.html

Extract the "taking on new client" modal into a separate partial to improve code reusability and maintainability. This change removes duplicate code from multiple files and centralizes the modal logic, making it easier to update and manage. Additionally, the blog section now dynamically displays the latest blog post, enhancing the site's content freshness and engagement.

♻️ (layouts): refactor client modal into a partial for reuse

---

site/content/company/book-online/index.md
site/layouts/partials/delivery-parts/deliveryfound-summery.html

✨📝 (book-online/index.md, deliveryfound-summery.html): add links for improved navigation and user engagement
Add a link to the "Working with us" page in the booking section to provide users with more information about the collaboration process. Introduce a new button for private or corporate sessions in the delivery summary to encourage direct engagement. Additionally, refactor the Mailchimp form HTML for better readability and maintainability. These changes aim to enhance user experience by providing clear navigation paths and encouraging interaction with the content.

Private class button to book meeting, and link to "Working with us" on that page

---

site/layouts/categories/list.html
site/layouts/tags/list.html

✨ (layouts): add resource type badge to category and tag cards
Add a badge displaying the resource type to both category and tag cards. This provides users with additional context about the type of content they are viewing, enhancing the user experience by making resource types immediately visible. Additionally, correct the template definition in categories/list.html to ensure proper rendering.

Add badges

---

site/content/resources/blog/2025/2025-03-03-measuring-individual-cycle-time-is-killing-your-flow/data.index.classifications.json
site/content/resources/blog/2025/2025-03-03-measuring-individual-cycle-time-is-killing-your-flow/index.md

📝 (blog): add new blog post on measuring cycle time in Kanban
Introduce a new blog post titled "Why Measuring Individual Cycle Time is Killing Your Flow (And What to Do Instead)" to educate readers on the pitfalls of focusing on individual cycle time in Kanban systems. The post emphasizes the importance of system-wide metrics like flow efficiency, work in progress limits, and throughput to improve overall workflow efficiency. It aims to shift the focus from individual performance to systemic improvements, aligning with Kanban principles and promoting better team dynamics and collaboration.

BLOG: Why Measuring Individual Cycle Time is Killing Your Flow (And What to Do Instead)

---

.powershell/_includes/ClassificationHelpers.ps1

♻️ (ClassificationHelpers.ps1): refactor cache removal logic and add age limit for catalog items
Introduce a new variable `$watermarkAgeLimit` to filter catalog items based on age, ensuring only items older than a specified number of days are considered for refresh. This change helps manage the cache more efficiently by focusing on outdated items. Additionally, refactor the cache removal logic to ensure the cache file is only updated when necessary, reducing unnecessary writes and improving performance.

Enable age check on watermark refresh... adds rolling watermark of 20 days for now... should increase later.

---

site/layouts/partials/main-menu-resources.html
site/layouts/resources/list.html

✨ (resources): add display for future resources in non-production environments
Remove unnecessary whitespace in main-menu-resources.html for cleaner code. Introduce a new feature in resources/list.html to display future resources when not in production. This helps developers and content managers preview upcoming resources, ensuring they are aware of scheduled content and can make necessary adjustments before it goes live. The feature includes a count of future resources and displays the number of days until each resource is scheduled to be published.

Improve display

---

site/layouts/resources/signal.html

The parameter name was incorrect, causing issues in rendering the platform signals. Changing it from `platform_signal` to `platform_signals` aligns with the expected data structure and ensures that the signals are correctly iterated and displayed in the UI.

🐛 (signal.html): correct parameter name from platform_signal to platform_signals

---

site/layouts/partials/infrastructure/seo.html

📝 (seo.html): fix JSON syntax by adding a missing comma
A missing comma in the JSON structure is corrected to ensure valid JSON syntax. This change prevents potential parsing errors and ensures the SEO configuration is correctly interpreted by search engines and other tools.

Fix for SameAs

---

site/content/resources/blog/2025/2025-08-04-telling-people-what-to-do-is-not-leadership-its-a-failure-of-system-design/index.md

📝 (blog): enhance content on pull systems and WIP limits in leadership blog
Improve the blog post by expanding on the benefits of pull systems and WIP limits. Clarify how push systems undermine team autonomy and ownership, leading to reactive work environments. Emphasize the importance of pull systems in fostering accountability and sustainable delivery. The changes aim to provide a deeper understanding of how system design impacts team dynamics and leadership effectiveness.

FEEDBACK: Telling People What to Do Is Not Leadership. It’s a Failure of System Design.

---

site/content/resources/blog/_index.md
site/content/resources/case-studies/_index.md
site/content/resources/engineering-notes/_index.md
site/content/resources/guides/_index.md
site/content/resources/learning-series/_index.md
site/content/resources/newsletters/_index.md
site/content/resources/podcast/_index.md
site/content/resources/principles/_index.md
site/content/resources/recipes/_index.md
site/content/resources/signals/_index.md
site/content/resources/videos/_index.md
site/content/resources/workshops/_index.md
site/layouts/resources/list.html

This pull request refactors the `resourceTypes` parameter across multiple content files and updates its usage in the layout logic. The changes standardize the use of `resourceType` instead of `resourceTypes` and ensure consistency in filtering logic within the layout templates.
* **Content Files:** Replaced `resourceTypes` with `resourceType` in metadata across several resource content files, such as `blog`, `case-studies`, `engineering-notes`, `guides`, and others. This change improves consistency and simplifies metadata definitions. [[1]](diffhunk://#diff-44e84645674789b42f6990de35a33a89434be20601c9d9bdcaafdf8ea9e21b9bL9-L10) [[2]](diffhunk://#diff-b8636106793930a25e66e29d73620ce9e5994cfb0bce00c2b0526d2ee8c91373L6) [[3]](diffhunk://#diff-aaaeec0628159a44fc166c55e5767cc9f1ab1b428fab495fde …

Fix for Blog + Refactor

---

site/layouts/partials/components/pages/header.html

- switch h1 and h2 content to improve semantic structure of the page headers
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nkdAgility/NKDAgility.com/530)

💄 style(header): swap header levels for semantic clarity

---

site/layouts/baseof.html

This pull request updates the conditional logic in the `site/layouts/baseof.html` file to ensure that certain scripts and tags are included only in the "preview" and "production" environments, instead of being excluded solely in the "development" environment.
* Updated the condition for including the Termly.io script to check if the environment is "preview" or "production" (`site/layouts/baseof.html`, line 8).
* Updated the condition for including the Google Tag Manager (noscript) tag to check if the environment is "preview" or "production" (`site/layouts/baseof.html`, line 32).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nkdAgility/NKDAgility.com/562)

Update environment checks for script inclusion in baseof.html
